version: "3.4"

networks:
  paragon-on-prem:
    driver: bridge

services:
  cerberus:
    container_name: paragon-cerberus
    image: useparagon/on-prem:latest
    command: ./cerberus
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${CERBERUS_PORT:-1700}:${CERBERUS_PORT:-1700}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M

  connect:
    container_name: paragon-connect
    image: useparagon/on-prem:latest
    command: ./connect
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${CONNECT_PORT:-1707}:${CONNECT_PORT:-1707}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M

  dashboard:
    container_name: paragon-dashboard
    image: useparagon/on-prem:latest
    command: ./dashboard
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${DASHBOARD_PORT:-1704}:${DASHBOARD_PORT:-1704}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M

  hercules:
    container_name: paragon-hercules
    image: useparagon/on-prem:latest
    command: ./hercules
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${HERCULES_PORT:-1701}:${HERCULES_PORT:-1701}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WORKER_CPU:-1.75}"
    mem_limit: ${DOCKER_WORKER_MEMORY:-6144}M

  hermes:
    container_name: paragon-hermes
    image: useparagon/on-prem:latest
    command: ./hermes
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${HERMES_PORT:-1702}:${HERMES_PORT:-1702}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M

  passport:
    container_name: paragon-passport
    image: useparagon/on-prem:latest
    command: ./passport
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${PASSPORT_PORT:-1706}:${PASSPORT_PORT:-1706}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M

  zeus:
    container_name: paragon-zeus
    image: useparagon/on-prem:latest
    command: ./zeus
    env_file: ./.env-docker
    networks:
      - paragon-on-prem
    ports:
      - "${ZEUS_PORT:-1703}:${ZEUS_PORT:-1703}"
    volumes:
      - ./volume:/var/paragon
    restart: unless-stopped
    cpus: "${DOCKER_WEB_CPU:-0.25}"
    mem_limit: ${DOCKER_WEB_MEMORY:-1024}M
